name: 'Markdown To Confluence'
branding:
  icon: 'book-open'
  color: 'blue'
description: 'Convert markdown pages from a git repository to pages on Confluence'
inputs:
  confluence_user: #User that will post pages
    description: 'Confluence User'
    required: true
  confluence_password: #API Password created for user
    required: true
  confluence_space: #The space in which the page needs to be added
    required: true
  confluence_api_url: #API Url 
    required: true
  confluence_ancestor_id:
    required: true
  markdown_folder:
    description: #The folder that contains markdown files to be pushed to confluence
    default: './docs'
    required: true
  